# Generated by Django 2.2 on 2020-02-23 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 6, 49, 30, 623851)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_on',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
