# Generated by Django 2.2 on 2020-03-02 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_guest',
        ),
    ]
