# Generated by Django 2.2 on 2020-02-23 06:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200223_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 6, 50, 38, 955996, tzinfo=utc)),
        ),
    ]
